#!/usr/bin/env bash
# Bash script installs nginx on a web server
# and redirects
sudo apt-get update
sudo apt-get install nginx -y
echo "Holberton School" | sudo tee "/var/www/html/index.html"
cmd="\\\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "/server_name _;/a $cmd" /etc/nginx/sites-available/default
sudo service nginx restart
